# Generated by Django 3.0.7 on 2020-06-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=30)),
                ('totalcost', models.CharField(max_length=10)),
            ],
        ),
    ]
