# Generated by Django 3.0.7 on 2020-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaapp', '0003_customerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
