# Generated by Django 3.0.7 on 2020-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaapp', '0005_auto_20200707_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
