# Generated by Django 3.0.7 on 2020-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaapp', '0006_auto_20200707_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzaImage/'),
        ),
    ]
